apiVersion: v1
kind: Service

metadata:
  name: mongo-hlsvc
  labels:
    app: flagger
    service: mongo

spec:
  type: ClusterIP

  ports:
    - name: mongo
      port: 27017
      targetPort: 27017

  clusterIP: None
  selector:
    app: flagger
    service: mongo
