apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mongo
  labels:
    app: flagger
    service: mongo

spec:
  selector:
    matchLabels:
      app: flagger
      service: mongo
  serviceName: mongo-hlsvc
  replicas: 3

  template:
    metadata:
      labels:
        app: flagger
        service: mongo

    spec:
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - --bind_ip_all
            - --replSet
            - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume

  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
