version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    assignees:
      - waduhek

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    assignees:
      - waduhek
