apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-server
  labels:
    app: flagger
    service: api-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flagger
      service: api-server

  template:
    metadata:
      labels:
        app: flagger
        service: api-server

    spec:
      containers:
        - name: api-server
          image: waduhek/flagger:latest
          ports:
            - containerPort: 50051
