apiVersion: v1
kind: Service

metadata:
  name: api-server
  labels:
    app: flagger
    service: api-server

spec:
  type: NodePort

  selector:
    app: flagger
    service: api-server

  ports:
    - name: api-server-port
      port: 50051
