// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: proto/projectpb/project.proto

package projectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request to create a new project.
type CreateNewProjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the project.
	ProjectName string `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
}

func (x *CreateNewProjectRequest) Reset() {
	*x = CreateNewProjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_projectpb_project_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProjectRequest) ProtoMessage() {}

func (x *CreateNewProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_projectpb_project_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateNewProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_projectpb_project_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

// The response of creating a new project.
type CreateNewProjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateNewProjectResponse) Reset() {
	*x = CreateNewProjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_projectpb_project_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProjectResponse) ProtoMessage() {}

func (x *CreateNewProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_projectpb_project_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateNewProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_projectpb_project_proto_rawDescGZIP(), []int{1}
}

// The request to get the project key.
type GetProjectKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the project.
	ProjectName string `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
}

func (x *GetProjectKeyRequest) Reset() {
	*x = GetProjectKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_projectpb_project_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectKeyRequest) ProtoMessage() {}

func (x *GetProjectKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_projectpb_project_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectKeyRequest.ProtoReflect.Descriptor instead.
func (*GetProjectKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_projectpb_project_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectKeyRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

// The response of requesting the project key.
type GetProjectKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key for the project.
	ProjectKey string `protobuf:"bytes,1,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
}

func (x *GetProjectKeyResponse) Reset() {
	*x = GetProjectKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_projectpb_project_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectKeyResponse) ProtoMessage() {}

func (x *GetProjectKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_projectpb_project_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectKeyResponse.ProtoReflect.Descriptor instead.
func (*GetProjectKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_projectpb_project_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectKeyResponse) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

var File_proto_projectpb_project_proto protoreflect.FileDescriptor

var file_proto_projectpb_project_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x70,
	0x62, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x70, 0x62, 0x22, 0x3c, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x38, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x32, 0xba, 0x01, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x5b, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x4b, 0x65, 0x79, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x64, 0x75, 0x68, 0x65, 0x6b, 0x2f, 0x66, 0x6c, 0x61,
	0x67, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_projectpb_project_proto_rawDescOnce sync.Once
	file_proto_projectpb_project_proto_rawDescData = file_proto_projectpb_project_proto_rawDesc
)

func file_proto_projectpb_project_proto_rawDescGZIP() []byte {
	file_proto_projectpb_project_proto_rawDescOnce.Do(func() {
		file_proto_projectpb_project_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_projectpb_project_proto_rawDescData)
	})
	return file_proto_projectpb_project_proto_rawDescData
}

var file_proto_projectpb_project_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_projectpb_project_proto_goTypes = []interface{}{
	(*CreateNewProjectRequest)(nil),  // 0: projectpb.CreateNewProjectRequest
	(*CreateNewProjectResponse)(nil), // 1: projectpb.CreateNewProjectResponse
	(*GetProjectKeyRequest)(nil),     // 2: projectpb.GetProjectKeyRequest
	(*GetProjectKeyResponse)(nil),    // 3: projectpb.GetProjectKeyResponse
}
var file_proto_projectpb_project_proto_depIdxs = []int32{
	0, // 0: projectpb.Project.CreateNewProject:input_type -> projectpb.CreateNewProjectRequest
	2, // 1: projectpb.Project.GetProjectKey:input_type -> projectpb.GetProjectKeyRequest
	1, // 2: projectpb.Project.CreateNewProject:output_type -> projectpb.CreateNewProjectResponse
	3, // 3: projectpb.Project.GetProjectKey:output_type -> projectpb.GetProjectKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_projectpb_project_proto_init() }
func file_proto_projectpb_project_proto_init() {
	if File_proto_projectpb_project_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_projectpb_project_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewProjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_projectpb_project_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewProjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_projectpb_project_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_projectpb_project_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_projectpb_project_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_projectpb_project_proto_goTypes,
		DependencyIndexes: file_proto_projectpb_project_proto_depIdxs,
		MessageInfos:      file_proto_projectpb_project_proto_msgTypes,
	}.Build()
	File_proto_projectpb_project_proto = out.File
	file_proto_projectpb_project_proto_rawDesc = nil
	file_proto_projectpb_project_proto_goTypes = nil
	file_proto_projectpb_project_proto_depIdxs = nil
}
