resources:
  # MongoDB resources.
  - mongo/headless-service.yml
  - mongo/statefulset.yml
  # Redis resources.
  - redis/headless-service.yml
  - redis/configmap.yml
  - redis/statefulset.yml
  # API server resources.
  - flagger/service.yml
  - flagger/deployment.yml
