on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "stable"

jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: GolangCI lint
        uses: golangci/golangci-lint-action@v8

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test
